spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
